create table properties
(
	id int auto_increment
		primary key,
	name varchar(255) null
);

INTO watchphilia.properties (id, name) VALUES (129, ' 500m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (152, ' alarm');
INSERT INTO watchphilia.properties (id, name) VALUES (90, ' fusion design');
INSERT INTO watchphilia.properties (id, name) VALUES (167, ' Hesalite crystal');
INSERT INTO watchphilia.properties (id, name) VALUES (72, ' Indiglo night-light');
INSERT INTO watchphilia.properties (id, name) VALUES (29, ' Indiglo night-light');
INSERT INTO watchphilia.properties (id, name) VALUES (82, ' inspired by vintage watches');
INSERT INTO watchphilia.properties (id, name) VALUES (146, ' limited production');
INSERT INTO watchphilia.properties (id, name) VALUES (142, ' off-centered hours and minutes');
INSERT INTO watchphilia.properties (id, name) VALUES (182, ' slide rule');
INSERT INTO watchphilia.properties (id, name) VALUES (138, ' tantalum case');
INSERT INTO watchphilia.properties (id, name) VALUES (168, ' time-only display');
INSERT INTO watchphilia.properties (id, name) VALUES (121, ' Tough Solar');
INSERT INTO watchphilia.properties (id, name) VALUES (24, '100m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (78, '150m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (5, '200m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (155, '24-hour display');
INSERT INTO watchphilia.properties (id, name) VALUES (198, '30-lap memory');
INSERT INTO watchphilia.properties (id, name) VALUES (17, '300m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (156, '50m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (199, '600m water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (13, '80-hour power reserve');
INSERT INTO watchphilia.properties (id, name) VALUES (116, 'alarms');
INSERT INTO watchphilia.properties (id, name) VALUES (194, 'anti-magnetic');
INSERT INTO watchphilia.properties (id, name) VALUES (174, 'anti-magnetic protection');
INSERT INTO watchphilia.properties (id, name) VALUES (169, 'anti-magnetic soft-iron inner case');
INSERT INTO watchphilia.properties (id, name) VALUES (63, 'Art Deco design');
INSERT INTO watchphilia.properties (id, name) VALUES (22, 'Automatic chronograph ');
INSERT INTO watchphilia.properties (id, name) VALUES (141, 'Automatic flyback chronograph');
INSERT INTO watchphilia.properties (id, name) VALUES (103, 'Automatic in-house movement');
INSERT INTO watchphilia.properties (id, name) VALUES (8, 'Automatic movement');
INSERT INTO watchphilia.properties (id, name) VALUES (97, 'Automatic ultra-thin movement');
INSERT INTO watchphilia.properties (id, name) VALUES (177, 'avant-garde design');
INSERT INTO watchphilia.properties (id, name) VALUES (196, 'avant-garde design');
INSERT INTO watchphilia.properties (id, name) VALUES (153, 'backlight');
INSERT INTO watchphilia.properties (id, name) VALUES (7, 'backlight');
INSERT INTO watchphilia.properties (id, name) VALUES (19, 'Bauhaus design');
INSERT INTO watchphilia.properties (id, name) VALUES (104, 'Bauhaus-inspired design');
INSERT INTO watchphilia.properties (id, name) VALUES (137, 'blue chrome dial');
INSERT INTO watchphilia.properties (id, name) VALUES (145, 'bold design');
INSERT INTO watchphilia.properties (id, name) VALUES (102, 'British design');
INSERT INTO watchphilia.properties (id, name) VALUES (34, 'ceramic bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (36, 'chronometer certified');
INSERT INTO watchphilia.properties (id, name) VALUES (66, 'classic Breguet hands');
INSERT INTO watchphilia.properties (id, name) VALUES (41, 'classic design');
INSERT INTO watchphilia.properties (id, name) VALUES (80, 'classic pilot watch design');
INSERT INTO watchphilia.properties (id, name) VALUES (44, 'clean design');
INSERT INTO watchphilia.properties (id, name) VALUES (192, 'clean design');
INSERT INTO watchphilia.properties (id, name) VALUES (53, 'clean elegant design');
INSERT INTO watchphilia.properties (id, name) VALUES (21, 'Co-Axial movement');
INSERT INTO watchphilia.properties (id, name) VALUES (120, 'cocktail-inspired dial');
INSERT INTO watchphilia.properties (id, name) VALUES (101, 'COSC-certified');
INSERT INTO watchphilia.properties (id, name) VALUES (115, 'countdown timer');
INSERT INTO watchphilia.properties (id, name) VALUES (151, 'countdown timer');
INSERT INTO watchphilia.properties (id, name) VALUES (181, 'date and day display');
INSERT INTO watchphilia.properties (id, name) VALUES (31, 'date display');
INSERT INTO watchphilia.properties (id, name) VALUES (47, 'date function');
INSERT INTO watchphilia.properties (id, name) VALUES (9, 'day-date display');
INSERT INTO watchphilia.properties (id, name) VALUES (149, 'Digital display');
INSERT INTO watchphilia.properties (id, name) VALUES (200, 'distinctive &quot;Griffes&quot; or claws');
INSERT INTO watchphilia.properties (id, name) VALUES (79, 'distinctive design');
INSERT INTO watchphilia.properties (id, name) VALUES (42, 'domed crystal');
INSERT INTO watchphilia.properties (id, name) VALUES (33, 'domed glass');
INSERT INTO watchphilia.properties (id, name) VALUES (71, 'durable design');
INSERT INTO watchphilia.properties (id, name) VALUES (30, 'Eco-Drive technology (solar powered)');
INSERT INTO watchphilia.properties (id, name) VALUES (94, 'elegant and versatile design');
INSERT INTO watchphilia.properties (id, name) VALUES (35, 'elegant design');
INSERT INTO watchphilia.properties (id, name) VALUES (132, 'elegant sporty design');
INSERT INTO watchphilia.properties (id, name) VALUES (60, 'Elite in-house movement');
INSERT INTO watchphilia.properties (id, name) VALUES (164, 'EOL (end of life) indicator');
INSERT INTO watchphilia.properties (id, name) VALUES (183, 'exceptional craftsmanship');
INSERT INTO watchphilia.properties (id, name) VALUES (134, 'exceptional finishing');
INSERT INTO watchphilia.properties (id, name) VALUES (96, 'exquisite craftsmanship');
INSERT INTO watchphilia.properties (id, name) VALUES (175, 'exquisite guilloche dial');
INSERT INTO watchphilia.properties (id, name) VALUES (184, 'fusion of materials');
INSERT INTO watchphilia.properties (id, name) VALUES (147, 'futuristic design');
INSERT INTO watchphilia.properties (id, name) VALUES (193, 'gas tube illumination');
INSERT INTO watchphilia.properties (id, name) VALUES (95, 'Geneva Seal');
INSERT INTO watchphilia.properties (id, name) VALUES (143, 'grande seconde ');
INSERT INTO watchphilia.properties (id, name) VALUES (172, 'Grande Tapisserie&quot; pattern dial');
INSERT INTO watchphilia.properties (id, name) VALUES (65, 'guilloche dial');
INSERT INTO watchphilia.properties (id, name) VALUES (15, 'Hand wound mechanical movement');
INSERT INTO watchphilia.properties (id, name) VALUES (100, 'high demand and prestige');
INSERT INTO watchphilia.properties (id, name) VALUES (144, 'high-end finishing');
INSERT INTO watchphilia.properties (id, name) VALUES (48, 'High-performance quartz');
INSERT INTO watchphilia.properties (id, name) VALUES (49, 'historical design');
INSERT INTO watchphilia.properties (id, name) VALUES (26, 'iconic design');
INSERT INTO watchphilia.properties (id, name) VALUES (89, 'iconic Tank design');
INSERT INTO watchphilia.properties (id, name) VALUES (68, 'impeccable craftsmanship');
INSERT INTO watchphilia.properties (id, name) VALUES (106, 'impeccable finishing');
INSERT INTO watchphilia.properties (id, name) VALUES (18, 'In-house manual wind movement');
INSERT INTO watchphilia.properties (id, name) VALUES (180, 'Indiglo night-light');
INSERT INTO watchphilia.properties (id, name) VALUES (98, 'innovative materials');
INSERT INTO watchphilia.properties (id, name) VALUES (39, 'integrated bracelet');
INSERT INTO watchphilia.properties (id, name) VALUES (28, 'interchangeable straps');
INSERT INTO watchphilia.properties (id, name) VALUES (50, 'ISO 6425 certified');
INSERT INTO watchphilia.properties (id, name) VALUES (54, 'large crown');
INSERT INTO watchphilia.properties (id, name) VALUES (70, 'leather strap');
INSERT INTO watchphilia.properties (id, name) VALUES (81, 'legibility');
INSERT INTO watchphilia.properties (id, name) VALUES (55, 'legible dial');
INSERT INTO watchphilia.properties (id, name) VALUES (154, 'luminous hands');
INSERT INTO watchphilia.properties (id, name) VALUES (170, 'luminous hands and markers');
INSERT INTO watchphilia.properties (id, name) VALUES (189, 'luminous markers');
INSERT INTO watchphilia.properties (id, name) VALUES (93, 'luxury sports watch');
INSERT INTO watchphilia.properties (id, name) VALUES (157, 'Manual wind');
INSERT INTO watchphilia.properties (id, name) VALUES (59, 'Manual wind movement');
INSERT INTO watchphilia.properties (id, name) VALUES (139, 'Manual winding');
INSERT INTO watchphilia.properties (id, name) VALUES (108, 'marine chronometer heritage');
INSERT INTO watchphilia.properties (id, name) VALUES (185, 'maritime design');
INSERT INTO watchphilia.properties (id, name) VALUES (191, 'military specification');
INSERT INTO watchphilia.properties (id, name) VALUES (76, 'minimalist look');
INSERT INTO watchphilia.properties (id, name) VALUES (67, 'minimalist luxury');
INSERT INTO watchphilia.properties (id, name) VALUES (57, 'minimalist pilot design');
INSERT INTO watchphilia.properties (id, name) VALUES (188, 'moon phase');
INSERT INTO watchphilia.properties (id, name) VALUES (166, 'Moonwatch');
INSERT INTO watchphilia.properties (id, name) VALUES (123, 'mud-resistant');
INSERT INTO watchphilia.properties (id, name) VALUES (87, 'NASA-certified for space missions');
INSERT INTO watchphilia.properties (id, name) VALUES (136, 'no traditional hands');
INSERT INTO watchphilia.properties (id, name) VALUES (131, 'octagonal bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (186, 'off-centered dial');
INSERT INTO watchphilia.properties (id, name) VALUES (127, 'open heart dial');
INSERT INTO watchphilia.properties (id, name) VALUES (86, 'Oyster case');
INSERT INTO watchphilia.properties (id, name) VALUES (25, 'Oystersteel case');
INSERT INTO watchphilia.properties (id, name) VALUES (187, 'Panorama Date');
INSERT INTO watchphilia.properties (id, name) VALUES (126, 'perpetual calendar');
INSERT INTO watchphilia.properties (id, name) VALUES (83, 'pilot watch aesthetics');
INSERT INTO watchphilia.properties (id, name) VALUES (165, 'pilot-style dial');
INSERT INTO watchphilia.properties (id, name) VALUES (109, 'pioneering dive watch heritage');
INSERT INTO watchphilia.properties (id, name) VALUES (40, 'plastic case');
INSERT INTO watchphilia.properties (id, name) VALUES (107, 'power reserve indicator');
INSERT INTO watchphilia.properties (id, name) VALUES (11, 'Powermatic 80 movement');
INSERT INTO watchphilia.properties (id, name) VALUES (190, 'Powermatic 80 movement');
INSERT INTO watchphilia.properties (id, name) VALUES (45, 'Quartz chronograph');
INSERT INTO watchphilia.properties (id, name) VALUES (27, 'Quartz movement');
INSERT INTO watchphilia.properties (id, name) VALUES (91, 'racing-inspired design');
INSERT INTO watchphilia.properties (id, name) VALUES (113, 'Radio-controlled');
INSERT INTO watchphilia.properties (id, name) VALUES (171, 'reversible case');
INSERT INTO watchphilia.properties (id, name) VALUES (62, 'Reversible case');
INSERT INTO watchphilia.properties (id, name) VALUES (110, 'robust ');
INSERT INTO watchphilia.properties (id, name) VALUES (32, 'robust construction');
INSERT INTO watchphilia.properties (id, name) VALUES (92, 'rubber strap with tire ');
INSERT INTO watchphilia.properties (id, name) VALUES (16, 'sapphire crystal');
INSERT INTO watchphilia.properties (id, name) VALUES (119, 'see-through case back');
INSERT INTO watchphilia.properties (id, name) VALUES (4, 'Shock resistant');
INSERT INTO watchphilia.properties (id, name) VALUES (12, 'silicium balance spring');
INSERT INTO watchphilia.properties (id, name) VALUES (38, 'simple and elegant design');
INSERT INTO watchphilia.properties (id, name) VALUES (84, 'Single hand display');
INSERT INTO watchphilia.properties (id, name) VALUES (23, 'skeleton dial');
INSERT INTO watchphilia.properties (id, name) VALUES (197, 'skeletonized design');
INSERT INTO watchphilia.properties (id, name) VALUES (176, 'skeletonized dial');
INSERT INTO watchphilia.properties (id, name) VALUES (69, 'slide rule');
INSERT INTO watchphilia.properties (id, name) VALUES (179, 'slide rule');
INSERT INTO watchphilia.properties (id, name) VALUES (43, 'slim profile');
INSERT INTO watchphilia.properties (id, name) VALUES (162, 'small seconds');
INSERT INTO watchphilia.properties (id, name) VALUES (114, 'solar-powered');
INSERT INTO watchphilia.properties (id, name) VALUES (46, 'Soviet-era design');
INSERT INTO watchphilia.properties (id, name) VALUES (128, 'space-tested design');
INSERT INTO watchphilia.properties (id, name) VALUES (99, 'sport-inspired ');
INSERT INTO watchphilia.properties (id, name) VALUES (52, 'sporty design');
INSERT INTO watchphilia.properties (id, name) VALUES (105, 'Spring Drive movement');
INSERT INTO watchphilia.properties (id, name) VALUES (130, 'square case');
INSERT INTO watchphilia.properties (id, name) VALUES (111, 'stainless steel case');
INSERT INTO watchphilia.properties (id, name) VALUES (6, 'stopwatch');
INSERT INTO watchphilia.properties (id, name) VALUES (75, 'Swiss design');
INSERT INTO watchphilia.properties (id, name) VALUES (51, 'tachymeter');
INSERT INTO watchphilia.properties (id, name) VALUES (161, 'tachymeter bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (61, 'thin case');
INSERT INTO watchphilia.properties (id, name) VALUES (148, 'three-dimensional horology');
INSERT INTO watchphilia.properties (id, name) VALUES (173, 'time-only display');
INSERT INTO watchphilia.properties (id, name) VALUES (195, 'tonneau case');
INSERT INTO watchphilia.properties (id, name) VALUES (178, 'torque indicator');
INSERT INTO watchphilia.properties (id, name) VALUES (140, 'traditional Breguet aesthetics');
INSERT INTO watchphilia.properties (id, name) VALUES (122, 'Triple Sensor');
INSERT INTO watchphilia.properties (id, name) VALUES (85, 'tritium gas tubes for night visibility');
INSERT INTO watchphilia.properties (id, name) VALUES (124, 'tritium illumination');
INSERT INTO watchphilia.properties (id, name) VALUES (133, 'ultra-slim design');
INSERT INTO watchphilia.properties (id, name) VALUES (125, 'ultra-thin design');
INSERT INTO watchphilia.properties (id, name) VALUES (14, 'unidirectional bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (118, 'unidirectional bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (158, 'unidirectional rotating bezel');
INSERT INTO watchphilia.properties (id, name) VALUES (135, 'Unique carousel movement');
INSERT INTO watchphilia.properties (id, name) VALUES (74, 'Unique two-second stop feature');
INSERT INTO watchphilia.properties (id, name) VALUES (117, 'various color options');
INSERT INTO watchphilia.properties (id, name) VALUES (73, 'vintage design');
INSERT INTO watchphilia.properties (id, name) VALUES (58, 'vintage feel');
INSERT INTO watchphilia.properties (id, name) VALUES (77, 'vintage inspired design');
INSERT INTO watchphilia.properties (id, name) VALUES (10, 'water resistance');
INSERT INTO watchphilia.properties (id, name) VALUES (20, 'water-resistant');
INSERT INTO watchphilia.properties (id, name) VALUES (112, 'world time function');
